server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: ${DB_NEO4J_CONNECTION}
    authentication:
      username: ${DB_NEO4J_USERNAME}
      password: ${DB_NEO4J_PASSWORD}
